package com.gcm.work.dao.mapper;

import com.gcm.work.model.Apply;
import com.gcm.work.model.ApplyExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ApplyMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apply
	 * @mbggenerated
	 */
	int countByExample(ApplyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apply
	 * @mbggenerated
	 */
	int deleteByExample(ApplyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apply
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer sid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apply
	 * @mbggenerated
	 */
	int insert(Apply record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apply
	 * @mbggenerated
	 */
	int insertSelective(Apply record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apply
	 * @mbggenerated
	 */
	List<Apply> selectByExample(ApplyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apply
	 * @mbggenerated
	 */
	Apply selectByPrimaryKey(Integer sid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apply
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Apply record, @Param("example") ApplyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apply
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Apply record, @Param("example") ApplyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apply
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Apply record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apply
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Apply record);

	List<Apply> findAll();
}