package com.gcm.work.dao.mapper;

import com.gcm.work.model.Eboard;
import com.gcm.work.model.EboardExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface EboardMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table eboard
	 * @mbggenerated  Sat Mar 25 14:19:20 CST 2017
	 */
	int countByExample(EboardExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table eboard
	 * @mbggenerated  Sat Mar 25 14:19:20 CST 2017
	 */
	int deleteByExample(EboardExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table eboard
	 * @mbggenerated  Sat Mar 25 14:19:20 CST 2017
	 */
	int deleteByPrimaryKey(Integer eid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table eboard
	 * @mbggenerated  Sat Mar 25 14:19:20 CST 2017
	 */
	int insert(Eboard record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table eboard
	 * @mbggenerated  Sat Mar 25 14:19:20 CST 2017
	 */
	int insertSelective(Eboard record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table eboard
	 * @mbggenerated  Sat Mar 25 14:19:20 CST 2017
	 */
	List<Eboard> selectByExample(EboardExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table eboard
	 * @mbggenerated  Sat Mar 25 14:19:20 CST 2017
	 */
	Eboard selectByPrimaryKey(Integer eid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table eboard
	 * @mbggenerated  Sat Mar 25 14:19:20 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Eboard record, @Param("example") EboardExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table eboard
	 * @mbggenerated  Sat Mar 25 14:19:20 CST 2017
	 */
	int updateByExample(@Param("record") Eboard record, @Param("example") EboardExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table eboard
	 * @mbggenerated  Sat Mar 25 14:19:20 CST 2017
	 */
	int updateByPrimaryKeySelective(Eboard record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table eboard
	 * @mbggenerated  Sat Mar 25 14:19:20 CST 2017
	 */
	int updateByPrimaryKey(Eboard record);
}