package com.gcm.work.model;

import java.util.Date;

public class Apply {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column apply.sid
	 * @mbggenerated
	 */
	private Integer sid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column apply.realname
	 * @mbggenerated
	 */
	private String realname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column apply.job_address
	 * @mbggenerated
	 */
	private String jobAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column apply.job_name
	 * @mbggenerated
	 */
	private String jobName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column apply.job_salary
	 * @mbggenerated
	 */
	private Double jobSalary;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column apply.release_time
	 * @mbggenerated
	 */
	private Date releaseTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column apply.company_name
	 * @mbggenerated
	 */
	private String companyName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column apply.sid
	 * @return  the value of apply.sid
	 * @mbggenerated
	 */
	public Integer getSid() {
		return sid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column apply.sid
	 * @param sid  the value for apply.sid
	 * @mbggenerated
	 */
	public void setSid(Integer sid) {
		this.sid = sid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column apply.realname
	 * @return  the value of apply.realname
	 * @mbggenerated
	 */
	public String getRealname() {
		return realname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column apply.realname
	 * @param realname  the value for apply.realname
	 * @mbggenerated
	 */
	public void setRealname(String realname) {
		this.realname = realname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column apply.job_address
	 * @return  the value of apply.job_address
	 * @mbggenerated
	 */
	public String getJobAddress() {
		return jobAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column apply.job_address
	 * @param jobAddress  the value for apply.job_address
	 * @mbggenerated
	 */
	public void setJobAddress(String jobAddress) {
		this.jobAddress = jobAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column apply.job_name
	 * @return  the value of apply.job_name
	 * @mbggenerated
	 */
	public String getJobName() {
		return jobName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column apply.job_name
	 * @param jobName  the value for apply.job_name
	 * @mbggenerated
	 */
	public void setJobName(String jobName) {
		this.jobName = jobName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column apply.job_salary
	 * @return  the value of apply.job_salary
	 * @mbggenerated
	 */
	public Double getJobSalary() {
		return jobSalary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column apply.job_salary
	 * @param jobSalary  the value for apply.job_salary
	 * @mbggenerated
	 */
	public void setJobSalary(Double jobSalary) {
		this.jobSalary = jobSalary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column apply.release_time
	 * @return  the value of apply.release_time
	 * @mbggenerated
	 */
	public Date getReleaseTime() {
		return releaseTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column apply.release_time
	 * @param releaseTime  the value for apply.release_time
	 * @mbggenerated
	 */
	public void setReleaseTime(Date releaseTime) {
		this.releaseTime = releaseTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column apply.company_name
	 * @return  the value of apply.company_name
	 * @mbggenerated
	 */
	public String getCompanyName() {
		return companyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column apply.company_name
	 * @param companyName  the value for apply.company_name
	 * @mbggenerated
	 */
	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}
}