package com.gcm.work.model;

public class Company {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column company.cid
	 * @mbggenerated
	 */
	private Integer cid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column company.company_name
	 * @mbggenerated
	 */
	private String companyName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column company.company_type
	 * @mbggenerated
	 */
	private String companyType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column company.company_login_name
	 * @mbggenerated
	 */
	private String companyLoginName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column company.company_pwd
	 * @mbggenerated
	 */
	private String companyPwd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column company.company_address
	 * @mbggenerated
	 */
	private String companyAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column company.company_website
	 * @mbggenerated
	 */
	private String companyWebsite;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column company.company_desc
	 * @mbggenerated
	 */
	private String companyDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column company.emp_num
	 * @mbggenerated
	 */
	private String empNum;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.cid
	 * @return  the value of company.cid
	 * @mbggenerated
	 */
	public Integer getCid() {
		return cid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.cid
	 * @param cid  the value for company.cid
	 * @mbggenerated
	 */
	public void setCid(Integer cid) {
		this.cid = cid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.company_name
	 * @return  the value of company.company_name
	 * @mbggenerated
	 */
	public String getCompanyName() {
		return companyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.company_name
	 * @param companyName  the value for company.company_name
	 * @mbggenerated
	 */
	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.company_type
	 * @return  the value of company.company_type
	 * @mbggenerated
	 */
	public String getCompanyType() {
		return companyType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.company_type
	 * @param companyType  the value for company.company_type
	 * @mbggenerated
	 */
	public void setCompanyType(String companyType) {
		this.companyType = companyType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.company_login_name
	 * @return  the value of company.company_login_name
	 * @mbggenerated
	 */
	public String getCompanyLoginName() {
		return companyLoginName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.company_login_name
	 * @param companyLoginName  the value for company.company_login_name
	 * @mbggenerated
	 */
	public void setCompanyLoginName(String companyLoginName) {
		this.companyLoginName = companyLoginName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.company_pwd
	 * @return  the value of company.company_pwd
	 * @mbggenerated
	 */
	public String getCompanyPwd() {
		return companyPwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.company_pwd
	 * @param companyPwd  the value for company.company_pwd
	 * @mbggenerated
	 */
	public void setCompanyPwd(String companyPwd) {
		this.companyPwd = companyPwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.company_address
	 * @return  the value of company.company_address
	 * @mbggenerated
	 */
	public String getCompanyAddress() {
		return companyAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.company_address
	 * @param companyAddress  the value for company.company_address
	 * @mbggenerated
	 */
	public void setCompanyAddress(String companyAddress) {
		this.companyAddress = companyAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.company_website
	 * @return  the value of company.company_website
	 * @mbggenerated
	 */
	public String getCompanyWebsite() {
		return companyWebsite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.company_website
	 * @param companyWebsite  the value for company.company_website
	 * @mbggenerated
	 */
	public void setCompanyWebsite(String companyWebsite) {
		this.companyWebsite = companyWebsite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.company_desc
	 * @return  the value of company.company_desc
	 * @mbggenerated
	 */
	public String getCompanyDesc() {
		return companyDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.company_desc
	 * @param companyDesc  the value for company.company_desc
	 * @mbggenerated
	 */
	public void setCompanyDesc(String companyDesc) {
		this.companyDesc = companyDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.emp_num
	 * @return  the value of company.emp_num
	 * @mbggenerated
	 */
	public String getEmpNum() {
		return empNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.emp_num
	 * @param empNum  the value for company.emp_num
	 * @mbggenerated
	 */
	public void setEmpNum(String empNum) {
		this.empNum = empNum;
	}
}