package com.gcm.work.model;

public class Eboard {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column eboard.eid
	 * @mbggenerated  Sat Mar 25 14:19:20 CST 2017
	 */
	private Integer eid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column eboard.title
	 * @mbggenerated  Sat Mar 25 14:19:20 CST 2017
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column eboard.content
	 * @mbggenerated  Sat Mar 25 14:19:20 CST 2017
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column eboard.news
	 * @mbggenerated  Sat Mar 25 14:19:20 CST 2017
	 */
	private String news;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column eboard.eid
	 * @return  the value of eboard.eid
	 * @mbggenerated  Sat Mar 25 14:19:20 CST 2017
	 */
	public Integer getEid() {
		return eid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column eboard.eid
	 * @param eid  the value for eboard.eid
	 * @mbggenerated  Sat Mar 25 14:19:20 CST 2017
	 */
	public void setEid(Integer eid) {
		this.eid = eid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column eboard.title
	 * @return  the value of eboard.title
	 * @mbggenerated  Sat Mar 25 14:19:20 CST 2017
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column eboard.title
	 * @param title  the value for eboard.title
	 * @mbggenerated  Sat Mar 25 14:19:20 CST 2017
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column eboard.content
	 * @return  the value of eboard.content
	 * @mbggenerated  Sat Mar 25 14:19:20 CST 2017
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column eboard.content
	 * @param content  the value for eboard.content
	 * @mbggenerated  Sat Mar 25 14:19:20 CST 2017
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column eboard.news
	 * @return  the value of eboard.news
	 * @mbggenerated  Sat Mar 25 14:19:20 CST 2017
	 */
	public String getNews() {
		return news;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column eboard.news
	 * @param news  the value for eboard.news
	 * @mbggenerated  Sat Mar 25 14:19:20 CST 2017
	 */
	public void setNews(String news) {
		this.news = news;
	}
}