package com.gcm.work.model;

import java.util.Date;

public class Favorites {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column favorites.fid
	 * @mbggenerated  Wed Mar 22 08:54:53 CST 2017
	 */
	private Integer fid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column favorites.job_address
	 * @mbggenerated  Wed Mar 22 08:54:53 CST 2017
	 */
	private String jobAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column favorites.job_name
	 * @mbggenerated  Wed Mar 22 08:54:53 CST 2017
	 */
	private String jobName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column favorites.job_salary
	 * @mbggenerated  Wed Mar 22 08:54:53 CST 2017
	 */
	private Double jobSalary;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column favorites.release_time
	 * @mbggenerated  Wed Mar 22 08:54:53 CST 2017
	 */
	private Date releaseTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column favorites.company_name
	 * @mbggenerated  Wed Mar 22 08:54:53 CST 2017
	 */
	private String companyName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column favorites.realname
	 * @mbggenerated  Wed Mar 22 08:54:53 CST 2017
	 */
	private String realname;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column favorites.fid
	 * @return  the value of favorites.fid
	 * @mbggenerated  Wed Mar 22 08:54:53 CST 2017
	 */
	public Integer getFid() {
		return fid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column favorites.fid
	 * @param fid  the value for favorites.fid
	 * @mbggenerated  Wed Mar 22 08:54:53 CST 2017
	 */
	public void setFid(Integer fid) {
		this.fid = fid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column favorites.job_address
	 * @return  the value of favorites.job_address
	 * @mbggenerated  Wed Mar 22 08:54:53 CST 2017
	 */
	public String getJobAddress() {
		return jobAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column favorites.job_address
	 * @param jobAddress  the value for favorites.job_address
	 * @mbggenerated  Wed Mar 22 08:54:53 CST 2017
	 */
	public void setJobAddress(String jobAddress) {
		this.jobAddress = jobAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column favorites.job_name
	 * @return  the value of favorites.job_name
	 * @mbggenerated  Wed Mar 22 08:54:53 CST 2017
	 */
	public String getJobName() {
		return jobName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column favorites.job_name
	 * @param jobName  the value for favorites.job_name
	 * @mbggenerated  Wed Mar 22 08:54:53 CST 2017
	 */
	public void setJobName(String jobName) {
		this.jobName = jobName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column favorites.job_salary
	 * @return  the value of favorites.job_salary
	 * @mbggenerated  Wed Mar 22 08:54:53 CST 2017
	 */
	public Double getJobSalary() {
		return jobSalary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column favorites.job_salary
	 * @param jobSalary  the value for favorites.job_salary
	 * @mbggenerated  Wed Mar 22 08:54:53 CST 2017
	 */
	public void setJobSalary(Double jobSalary) {
		this.jobSalary = jobSalary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column favorites.release_time
	 * @return  the value of favorites.release_time
	 * @mbggenerated  Wed Mar 22 08:54:53 CST 2017
	 */
	public Date getReleaseTime() {
		return releaseTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column favorites.release_time
	 * @param releaseTime  the value for favorites.release_time
	 * @mbggenerated  Wed Mar 22 08:54:53 CST 2017
	 */
	public void setReleaseTime(Date releaseTime) {
		this.releaseTime = releaseTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column favorites.company_name
	 * @return  the value of favorites.company_name
	 * @mbggenerated  Wed Mar 22 08:54:53 CST 2017
	 */
	public String getCompanyName() {
		return companyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column favorites.company_name
	 * @param companyName  the value for favorites.company_name
	 * @mbggenerated  Wed Mar 22 08:54:53 CST 2017
	 */
	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column favorites.realname
	 * @return  the value of favorites.realname
	 * @mbggenerated  Wed Mar 22 08:54:53 CST 2017
	 */
	public String getRealname() {
		return realname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column favorites.realname
	 * @param realname  the value for favorites.realname
	 * @mbggenerated  Wed Mar 22 08:54:53 CST 2017
	 */
	public void setRealname(String realname) {
		this.realname = realname;
	}
}