package com.gcm.work.model;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.uid
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.login_name
	 */
	private String loginName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.login_pwd
	 */
	private String loginPwd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.gender
	 */
	private String gender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.telephone
	 */
	private String telephone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.email
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.descripte
	 */
	private String descripte;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.realname
	 */
	private String realname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.address
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.job_status
	 */
	private String jobStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.salary
	 */
	private Double salary;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.school
	 */
	private String school;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.uid
	 * @return  the value of user.uid
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.uid
	 * @param uid  the value for user.uid
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.login_name
	 * @return  the value of user.login_name
	 */
	public String getLoginName() {
		return loginName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.login_name
	 * @param loginName  the value for user.login_name
	 */
	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.login_pwd
	 * @return  the value of user.login_pwd
	 */
	public String getLoginPwd() {
		return loginPwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.login_pwd
	 * @param loginPwd  the value for user.login_pwd
	 */
	public void setLoginPwd(String loginPwd) {
		this.loginPwd = loginPwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.gender
	 * @return  the value of user.gender
	 */
	public String getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.gender
	 * @param gender  the value for user.gender
	 */
	public void setGender(String gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.telephone
	 * @return  the value of user.telephone
	 */
	public String getTelephone() {
		return telephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.telephone
	 * @param telephone  the value for user.telephone
	 */
	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.email
	 * @return  the value of user.email
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.email
	 * @param email  the value for user.email
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.descripte
	 * @return  the value of user.descripte
	 */
	public String getDescripte() {
		return descripte;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.descripte
	 * @param descripte  the value for user.descripte
	 */
	public void setDescripte(String descripte) {
		this.descripte = descripte;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.realname
	 * @return  the value of user.realname
	 */
	public String getRealname() {
		return realname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.realname
	 * @param realname  the value for user.realname
	 */
	public void setRealname(String realname) {
		this.realname = realname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.address
	 * @return  the value of user.address
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.address
	 * @param address  the value for user.address
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.job_status
	 * @return  the value of user.job_status
	 */
	public String getJobStatus() {
		return jobStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.job_status
	 * @param jobStatus  the value for user.job_status
	 */
	public void setJobStatus(String jobStatus) {
		this.jobStatus = jobStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.salary
	 * @return  the value of user.salary
	 */
	public Double getSalary() {
		return salary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.salary
	 * @param salary  the value for user.salary
	 */
	public void setSalary(Double salary) {
		this.salary = salary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.school
	 * @return  the value of user.school
	 */
	public String getSchool() {
		return school;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.school
	 * @param school  the value for user.school
	 */
	public void setSchool(String school) {
		this.school = school;
	}
}